package response

type Code string

var (
	UNAUTHORIZED                   Code = "UNAUTHORIZED"
	FORBIDDEN                      Code = "FORBIDDEN"
	CONCURRENT_SESSION_NOT_ALLOWED Code = "CONCURRENT_SESSION_NOT_ALLOWED"
	INVALID_PAYLOAD                Code = "INVALID_PAYLOAD"
	SESSION_EXPIRED                Code = "SESSION_EXPIRED"
	TOO_MANY_REQUESTS              Code = "TOO_MANY_REQUESTS"
	INTERNAL_SERVER_ERROR          Code = "INTERNAL_SERVER_ERROR"
	SUSPICIOUS_ACTIVITY_DETECTED   Code = "SUSPICIOUS_ACTIVITY_DETECTED"
	Ok                             Code = "Ok"
	TIMESTAMP_INVALID              Code = "TIMESTAMP_INVALID"
	SIGNATURE_INVALID              Code = "SIGNATURE_INVALID"
	SESSION_NOT_ACTIVE             Code = "SESSION_NOT_ACTIVE"
	PREREQUISITES_NOT_MET          Code = "PREREQUISITES_NOT_MET"
	SESSION_UPDATE_FAILED          Code = "SESSION_UPDATE_FAILED"
	MISSING_HEADERS                Code = "MISSING_HEADERS"
	DATABASE_ERROR                 Code = "DATABASE_ERROR"
	SESSION_CREATION_FAILED        Code = "SESSION_CREATION_FAILED"
	SESSION_STARTED                Code = "SESSION_STARTED"
)
